### ISSUE TITLE
Please, publish sources.jar, too

### ISSUE THREAD

**Issue by michalrus** [galarragas/spray-funnel#9]
Currently, we cannot jump-to-def in our IDEs of choice, because only the binary jars are published.

**Comment by galarragas** [comment]
Hi @michalrus, actually I'm having problems to put the sources on Conjars, I'll try to do some investigation but I suggest you to clone the project and attach the sources from the filesystem in the meantime...

**Comment by galarragas** [comment]
Hi @michalrus . Looks like with Conjars it is not possible. I published to Bintray too and that contains the sources. You just have to replace the conjars related resolver with my bintray one (`resolvers += Resolver.bintrayRepo("galarragas", "maven")` )

**Comment by galarragas** [comment]
Hi @michalrus, any feedback?

**Comment by michalrus** [comment]
Hey, @galarragas, thank you for your quick response and sorry for me staying a bit behind!

That’s great you switched to a provider that supports sources.jar. :+1: 

However, IntelliJ still says it’s unable to download the sources? I’ve cloned my project to a completely new location, still the same.

**Comment by galarragas** [comment]
Hi @michalrus, sorry to ask... did you change your build.sbt file to use the new repository?

**Comment by michalrus** [comment]
Haha, sure. =) Could you verify that your sample build.sbt works with `sbt updateClassifiers`?

```
> updateClassifiers
[warn]  [FAILED     ] com.pragmasoft#spray-funnel_2.10;1.1!spray-funnel_2.10.jar(src):  (0ms)
[warn] ==== local: tried
[warn]   /home/m/.ivy2/local/com.pragmasoft/spray-funnel_2.10/1.1/srcs/spray-funnel_2.10-sources.jar
[warn] ==== jcenter: tried
[warn]   https://jcenter.bintray.com/com/pragmasoft/spray-funnel_2.10/1.1/spray-funnel_2.10-1.1-sources.jar
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/pragmasoft/spray-funnel_2.10/1.1/spray-funnel_2.10-1.1-sources.jar
[warn] ==== Typesafe Releases: tried
[warn]   http://repo.typesafe.com/typesafe/releases/com/pragmasoft/spray-funnel_2.10/1.1/spray-funnel_2.10-1.1-sources.jar
[warn] ==== spray repo: tried
[warn]   http://repo.spray.io/com/pragmasoft/spray-funnel_2.10/1.1/spray-funnel_2.10-1.1-sources.jar
[warn] ==== bintray-galarragas-maven: tried
[warn]   https://dl.bintray.com/galarragas/maven/com/pragmasoft/spray-funnel_2.10/1.1/spray-funnel_2.10-1.1-sources.jar
```

**Comment by michalrus** [comment]
The last URL returns 404, while, perhaps, the sources should be just there.

https://dl.bintray.com/galarragas/maven/com/pragmasoft/spray-funnel_2.10/1.1/spray-funnel_2.10-1.1-sources.jar

**Comment by galarragas** [comment]
Aaah, you got me. I didn't published the spray 1.2.x version yet. Just did it sorry :-)

**Comment by michalrus** [comment]
Thank you. :smile_cat:

**Comment by galarragas** [comment]
Let me know if I can close when and if it works..

**Comment by michalrus** [comment]
Well, it works in sbt, doesn’t work in IntelliJ for some reason. Anyway, we can close, it’s IntelliJ’s fault now.
